repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
    -    id: ruff
    -    id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v2.3.1'
    hooks:
    -   id: mypy
        exclude: ^examples/.*$ # FIXME
        additional_dependencies: [
            pydantic~=2.0,
            pydantic-settings~=2.0,
            strenum,
            types-colorama,
            types-docutils,
            types-Pillow, types-psutil,
            types-Pygments,
            types-pywin32,
            types-PyYAML,
            types-regex,
            types-requests,
            types-setuptools,
            types-tabulate,
            types-tqdm,
            types-urllib3,
            horde_sdk==0.29.3,
            horde_model_reference==7.6.1,
        ]
