training_data: "./inference-time-data.json"
validation_data: "./inference-time-data-validation.json"
study_trials: 2000
study_version: "v25"
db_path: "optuna_studies.db"
num_epochs: 1000
patience: 25
min_number_of_epochs: 50
max_hidden_layers: 6
min_nodes_in_layer: 4
max_nodes_in_layer: 128
min_learning_rate: 1e-4
max_learning_rate: 1e-2
min_weight_decay: 1e-5
max_weight_decay: 1e-3
min_data_batch_size: 32
max_data_batch_size: 512
optuna_sampler: "samplers/auto_sampler"