# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.5.3.dev1+g82a4b82.d20230411'
__version_tuple__ = version_tuple = (0, 5, 3, 'dev1', 'g82a4b82.d20230411')
